---
title: "Factors + Group Activity!"
author: "Brianna Heggeseth"
logo: "images/mac.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
editor: visual
---

## Preparation {.unnumbered .smaller}

1.  Watch a [12 minute video](https://drive.google.com/file/d/1XPZxl_eM7FsXKj-5U7x8OAaIAS6Q4wM6/view?usp=sharing) before class starts (or at the beginning of class).

2.  Sit with people you don't know well. Introduce yourself and discuss/assign group roles:

-   Facilitator: Make sure the group makes progress on the task
-   Reflector: Make sure that everyone in the group contributes positive; encourage participation from everyone (e.g. What do you think? Any ideas?)
-   Resource Manager: Make sure the group seeks out the resources it needs to complete the task
-   Communicator Manager: Take responsibility to facilitate communication with each other and to the larger class/instructor

## Announcements {.unnumbered .smaller}

**This week in MSCS**

-   Preceptor Training (if you are preceptor for another class!)
-   Wednesday 3:30pm: Math Problem Solving!
-   Thursday 11:15am: Coffee Break! Student Advisory Board Introductions!

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, tidy = FALSE, message = FALSE)
library(tidyverse)
library(ggplot2)
library(lubridate)
```

## Due this Week {.unnumbered .smaller}

-   7 (Reshaping) Today \[via Moodle\]
-   TT5 Friday night \[via Moodle\]
-   8 (Joins) Sunday night \[via Moodle\]


## Past Due {.unnumbered .smaller}

If you haven't turned in the following, do so soon:

-   Tidy Tuesday 4
-   Iterative Viz 0 (no extra work, submit 1 completed TT html file)
-   Reflection on Learning (in individual document shared with you)

If your spreadsheet says "No submission for assignment",

-   submit your assignment to Moodle
-   email Brianna indicating that you've submitted


## Template File {.unnumbered}

Download a template .Rmd of this activity. Put the file in a `Day_10` folder within your `COMP_STAT_112` folder.

-   This .Rmd only contains 1 exercise that you'll complete in a group.
-   Make sure all names are listed at the top of the file after `author:`
-   One member from the table will turn in the assignment to Moodle for Assignment 9 

## Recommendations {.unnumbered}

1. Each of you brainstorm some ideas
2. Play in your individual Rmd files.
3. After 10 minutes, come together to decide on a research question and a visualization plan. 
4. Create a Slack DM group to share code with each other.
5. One person needs to submit the final file, but all can by typing/working on their own machines. 

## After Class {.unnumbered}

Complete 

- Assignment 7 (Reshaping) for tonight and 
- Assignment 8 (Joins) for Sunday.

