---
title: "Written Communication: Crafting Sentences"
author: "Brianna Heggeseth"
logo: "images/mac.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
editor: visual
---

## Announcements {.unnumbered .smaller}

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggmap)
library(GGally)
```

**MSCS Happenings**

-   [MSCS Waitlist Info](https://www.macalester.edu/mscs/mscs-course-waitlists/)
-   [MSCS Student Instagram](https://www.instagram.com/macalestermscs/)
-   Nov 7 [TODAY] \@ 4:40pm, MSCS & Society Lecture, Geometry, Robots, and Society by Dr. Federico Ardila-Mantilla
-   See Board for Upcoming Visitor Talks!

**Outside MSCS**

-   [Mac Hub Events](https://docs.google.com/document/d/1kL-gNrtLwAcdaF5Vot4IW25Js2UvEIzRzFsHuRGrdqc/edit)

## Announcements {.unnumbered .smaller}

**Assignments**

-   13 (Regex) due Tuesday [tomorrow]

**Tidy Tuesday**

-   Complete 3 (minimum) before the end of the semester
    -   5 more weeks left!

**Iterative Viz**

-   IV1: Updated graphic past due.

## Crafting Sentences

Go to [Google Drive Folder](https://drive.google.com/drive/folders/1lIP4_Yjit19H7x2nX8j81IFQgTQQWCvL)

Open Communicating with Data (Chp 9) pdf.


## Read

Choose 1 section in Chapter 9 to read (9.1, 9.2, 9.3, or 9.4). 

- Each student in the group should read a different section.

- Once you've read the section, share with your group the main points of that section. 

## Revise

Go to [Google Drive Folder](https://drive.google.com/drive/folders/1lIP4_Yjit19H7x2nX8j81IFQgTQQWCvL)

Open Writing Sentences about Data for your section.

- Each group is assigned a sentence to revise together.

- Write your revision 
  - if your table is in the front of the room, write on Revision 1; 
  - if in back, writing on Revision 2


## Read

Now each of you read section 9.5.

## Revise

Go to back to Writing Sentences about Data for your section.

- Read the original text. 
  - Identify the "blogger style" in the text below.

- In the Front or Back of Room sections, add comments and highlight text or phrases in red that you would remove if you wanted a more formal writing style.

## After Class {.unnumbered}

-   We'll continue working on written communication on Wednesday.

**Assignments**

-   Regex
-   EDA on project data
