---
title: "Written Communication: Peer Review"
author: "Brianna Heggeseth"
logo: "images/mac.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
editor: visual
---

## Announcements {.unnumbered .smaller}

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggmap)
library(GGally)
```

**MSCS Happenings**

-   [MSCS Waitlist Info](https://www.macalester.edu/mscs/mscs-course-waitlists/)
-   [MSCS Student Instagram](https://www.instagram.com/macalestermscs/)

**Outside MSCS**

-   [Mac Hub Events](https://docs.google.com/document/d/1kL-gNrtLwAcdaF5Vot4IW25Js2UvEIzRzFsHuRGrdqc/edit)

## Announcements {.unnumbered .smaller}

**Assignments**

-   13 (Regex) past due.
-   14 (One Number Story) due next week.

**Tidy Tuesday**

-   Complete 3 (minimum) before the end of the semester
    -   5 more weeks left!
-   [Tidy Tuesday Collection](https://docs.google.com/presentation/d/1fFcL0JRvGYz6AxGJ9Y53m6VBDX4J4i605jcC3qqVMNk/edit#slide=id.p)

**Iterative Viz**

-   IV1: Updated graphic past due.

## Reflect

At your table, 

- reflect on how it felt to write this One Number Story
- how do you feel about the rough draft you have today



## Peer Feedback

Go to [Google Drive Folder](https://drive.google.com/drive/folders/1lIP4_Yjit19H7x2nX8j81IFQgTQQWCvL).

-   Open Comp/Stat 112 Peer Feedback document.

## Peer Feedback

Stand up and find someone else in the class that is not in your project group

- Introduce yourself (if needed)
- Share your Google Doc with them (with editing access)

## Peer Feedback

1. Read first
2. Give feedback (prompts/action items in the Peer Feedback document)
3. Discuss (focus on lifting each other up while discussing ideas for improvement)


## One Number Story

Take this feedback and revise.

- Due Tuesday Nov 15
- Turn in by giving me editor access to your Google Doc (with the document title "Comp/Stat 112 One Number Story - NAME")

## After Class {.unnumbered}

-   Work in One Number Story
-   EDA on project data

**Next Week**

We'll focus on visuals to help us communicate our story

  - Monday: we'll work on creating a visualization from the project
  - Weds/Friday: we'll present the visual to a small group and give/get peer feedback

