---
title: "Present & Critique"
author: "Brianna Heggeseth"
logo: "images/mac.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
editor: visual
---

## Announcements {.unnumbered .smaller}

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
```

**MSCS Happenings**

-   [MSCS Waitlist Info](https://www.macalester.edu/mscs/mscs-course-waitlists/)
-   [MSCS Student Instagram](https://www.instagram.com/macalestermscs/)

**Outside MSCS**

-   [Mac Hub Events](https://docs.google.com/document/d/1kL-gNrtLwAcdaF5Vot4IW25Js2UvEIzRzFsHuRGrdqc/edit)

## Announcements {.unnumbered .smaller}

**Assignments**

-   13 (Regex) past due.
-   14 (One Number Story) past due

**Tidy Tuesday**

-   Complete 3 (minimum) before the end of the semester
    -   4 more weeks left!
-   [Tidy Tuesday Collection](https://docs.google.com/presentation/d/1fFcL0JRvGYz6AxGJ9Y53m6VBDX4J4i605jcC3qqVMNk/edit#slide=id.p)

**Iterative Viz**

-   IV1: Updated graphic past due.

## Effective Visuals {.smaller}

Let's review from the [beginning of semester](https://bcheggeseth.github.io/112_fall_2022/effective-visualizations.html).

-   Be ethical and honest
-   Consider glyph choice
    -   easy or hard to perceive?
-   Consider color choices
    -   color blind friendly? cultural associations?
-   Facilitate comparison
    -   e.g. position through order on axis or faceting, calculate and present the difference or ratio
-   Use contrasts to draw attention
    -   e.g. yellow, red, orange draw attention in nature of green, brown, blue

## Presenting a Visual {.smaller}

When preparing to present a visualization, consider:

-   What context does the audience need to understand the visual? (W's?)
-   Does the visual have enough text annotation and guides to be understood with minimal explanation?
-   What aspects of the visual should you explain to provide necessary orientation?
    -   Walk through guides (axes, color legend, etc.)
-   What aspects of the visual do you want to draw attention to?
    -   What comparison are you wanting to highlight?

## Today

In small groups of 3-4 people,

-   you'll present your visualization (2 minutes)
-   discuss as a group ways of improving the visualization to make it more effective (8 minutes)
    -   comment on the good features of the graphic first
    -   offer concrete suggestions about the visualization
    -   offer ideas and questions that you have about the visual and data

*Once your group is done, use this time to update your graphic based on that feedback.*

## Group Creation

Count off in your project groups (1,2,3,4).

-   If you are a group of 2, count off (3,4)
-   If you are solo, go to #4.

I may make a few adjustments.

-   If you are on the West side of the room (go to the table W#)
-   If you are on the East side of the room (go to the table E#)

## After Class {.unnumbered}

-   Incorporate that feedback and update your visual for Friday!
