---
title: "Project Work"
author: "Brianna Heggeseth"
logo: "images/mac.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
editor: visual
---

## Announcements {.unnumbered .smaller}

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggmap)
library(GGally)
```

**MSCS Happenings**

-   [MSCS Waitlist Info](https://www.macalester.edu/mscs/mscs-course-waitlists/)
-   [MSCS Student Instagram](https://www.instagram.com/macalestermscs/)
-   [MSCS Mentoring Program](https://docs.google.com/forms/d/e/1FAIpQLSczyKV1hOrfi0dQscSFSPhfgc_LJUl4TOGdb6B4Q5lQF-TmuQ/viewform?vc=0&c=0&w=1&flr=0)
-   Nov 7 \@ 4:40pm, MSCS & Society Lecture, Geometry, Robots, and Society by Dr. Federico Ardila-Mantilla
-   See Board for Upcoming Visitor Talks!

**Outside MSCS**

-   [Mac Hub Events](https://docs.google.com/document/d/1kL-gNrtLwAcdaF5Vot4IW25Js2UvEIzRzFsHuRGrdqc/edit)
-   [Fall Data Challenge](https://thisisstatistics.org/falldatachallenge/) sponsored by the American Statistical Association (Deadline: Nov 6)
-   [Electronic Undergraduate Statistics Conference](https://www.causeweb.org/usproc/eusr/2022) (Nov 4th, free!)

## Announcements {.unnumbered .smaller}

**Assignments**

-   11 (EDA) past due
-   12 (Data Import) past due
-   13 (Regex) due next week

**Tidy Tuesday**

-   Complete 3 (minimum) before the end of the semester
    -   6 more weeks left!

**Iterative Viz**

-   IV1: Updated graphic by Friday
    -   If you want feedback on IV0, turn it in and email Brianna.

## Project Work

[Project Guidelines](https://docs.google.com/document/d/1MhfsjvYO2K1kuZlNflXuGoX3az85-7QVnK9Yzscuc78/edit?usp=sharing)

What should you be doing now?

-   Agreeing to a broad research question
-   Getting data into RStudio
-   Starting Exploratory Data Analysis (EDA)

By the end of class, fill out this [check in form](https://forms.gle/m61XgqpUeHy4JgQr6)

## After Class {.unnumbered}

-   We'll continue working on projects as we consider data communication next week.

**Assignments**

-   EDA (flights)
-   Data Import (your own data)
-   Regex
-   Iterative Viz
